language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2_lab2_matrix
  - make -j
  - ls
  - ./test/Matrix_Test
notifications:
  email: false
